[tool.pytest.ini_options]
addopts = """--durations=20 --doctest-modules -ra --cov-report= --tb=short \
    --cov-branch --doctest-ignore-import-errors --junit-xml=junit-results.xml \
    --color=yes --capture=sys --cov=h5io"""
junit_family = "xunit2"

[tool.ruff]
select = ["E", "F", "W", "D", "I"]
exclude = ["__init__.py"]

[tool.ruff.pydocstyle]
convention = "numpy"
