name: Build
on:
  release:
    types: [published]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip twine setuptools wheel
      - run: python setup.py sdist bdist_wheel
      - run: twine check --strict dist/*
      - run: |
          echo "Triggered by: ${{ github.event_name }}"
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  # PyPI on release
  pypi-publish:
    needs: package
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/<your-pypi-project-name>
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'release'
