name: 'Tests'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  pytest:
    name: '${{ matrix.os }} / ${{ matrix.python }}'
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -e {0}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: '3.13'
          - os: ubuntu-latest
            python: '3.12'
          - os: macos-latest
            python: '3.10'
          - os: windows-latest
            python: '3.8'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: ${{ matrix.python == '3.13' }}
      # Have to wait for https://github.com/scipy/scipy/pull/21000 for SciPy, something else for Pandas
      - run: pip install scipy pandas
        if: matrix.python != '3.13'
      # This will take a while on 3.13 because of https://github.com/h5py/hdf5-manylinux/issues/11
      - run: sudo apt install libhdf5-dev && pip install "numpy>=2.1.0.dev0" h5py --only-binary="numpy" --extra-index-url "https://pypi.anaconda.org/scientific-python-nightly-wheels/simple"
        if: matrix.python == '3.13'
      # Pin NumPy for https://github.com/PyTables/PyTables/issues/1083
      - run: pip install tables "numpy<2"  # segfaults on macOS sometimes
        if: matrix.os != 'macos-latest' && matrix.python != '3.13'
      - run: pip install pytest pytest-cov --only-binary="numpy,h5py" -e .
      - run: pytest -v h5io
      - uses: codecov/codecov-action@v4
